//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by [Tool]__LevelEditor.rc
//
#define IDR_MANIFEST                    1
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_LEVEL_EDIT_DIALOG           105
#define IDD_MOB_SET_PAGE                106
#define IDD_LEVEL_MAIN_PAGE             107
#define IDD_MOB_SCH_PAGE                108
#define IDD_LAND_GATE_PAGE              109
#define IDD_CROW_TREE_PAGE              110
#define IDD_REQUIRE_PAGE                111
#define IDD_ITEM_TREE_PAGE              112
#define IDD_SKILL_TREE_PAGE             113
#define IDD_GATE_LIST_PAGE              114
#define IDD_SINGLE_EFFECT_PAGE          115
#define IDD_LAND_MARK_PAGE              116
#define IDD_ETC_FUNC_PAGE               117
#define IDD_QUEST_DIALOG                118
#define IDR_MAINFRAME                   128
#define IDR_LevelEditorTYPE             129
#define IDS_PROPSHT_CAPTION             129
#define IDC_COMBO_PAGE                  1000
#define IDC_STATIC_CONTROL              1001
#define IDC_BUTTON_FNAME                1002
#define IDC_EDIT_FNAME                  1003
#define IDC_BUTTON_WLDFILE              1004
#define IDC_EDIT_WLDFILE                1005
#define IDC_COMBO_DIV                   1006
#define IDC_EDIT_DIV                    1007
#define IDC_BUTTON_CREATE_QTREE         1008
#define IDC_CHECK_RENDER_QTREE          1009
#define IDC_CHECK_SHOW_CROWSCHDL        1010
#define IDC_BUTTON_PLAY                 1011
#define IDC_BUTTON_STOP                 1012
#define IDC_EDIT_MOB_COPY               1013
#define IDC_LIST_MOB                    1014
#define IDC_BUTTON_MOB_NEW              1015
#define IDC_BUTTON_MOB_EDIT             1016
#define IDC_BUTTON_MOB_DEL              1017
#define IDC_BUTTON_GRP_NAME             1018
#define IDC_EDIT_GROUP_NAME             1019
#define IDC_CHECK_LEADER                1020
#define IDC_BUTTON_NAME_ID              1021
#define IDC_EDIT_NAME_ID                1022
#define IDC_BUTTON_CROW_ID              1023
#define IDC_EDIT_CROW_MID               1024
#define IDC_EDIT_CROW_SID               1025
#define IDC_BUTTON_GEN_TIME             1026
#define IDC_EDIT_GEN_TIME               1027
#define IDC_CHECK_SUNDAY                1028
#define IDC_CHECK_MONDAY                1029
#define IDC_CHECK_TUESDAY               1030
#define IDC_CHECK_WEDNESDAY             1031
#define IDC_CHECK_THURSDAY              1032
#define IDC_CHECK_FRIDAY                1033
#define IDC_CHECK_SATURDAY              1034
#define IDC_BUTTON_GENDEC_TIME          1035
#define IDC_EDIT_GEN_HOURS              1036
#define IDC_EDIT_GEN_MIN                1037
#define IDC_CHECK_RAND_POS              1038
#define IDC_BUTTON_FIND_POS             1039
#define IDC_SPIN_NUM                    1040
#define IDC_EDIT_NUM                    1041
#define IDC_SPIN_DIST                   1042
#define IDC_EDIT_DIST                   1043
#define IDC_BUTTON_REV_GATE             1044
#define IDC_EDIT_REV_GATE               1045
#define IDC_BUTTON_BUS                  1046
#define IDC_EDIT_BUS                    1047
#define IDC_BUTTON_SCHDL_MAN            1048
#define IDC_BUTTON_OK                   1049
#define IDC_BUTTON_CANCEL               1050
#define IDC_STATIC_EDIT_GROUP           1051
#define IDC_STATIC_NUM                  1052
#define IDC_STATIC_DIST                 1053
#define IDC_BUTTON_SCH_SET_COMPLET      1054
#define IDC_LIST_SCH                    1055
#define IDC_BUTTON_SCH_NEW              1056
#define IDC_BUTTONSCH_EDIT              1057
#define IDC_BUTTONSCH_MOVE              1058
#define IDC_BUTTON_SCH_DEL              1059
#define IDC_COMBO_SCH_ACT               1060
#define IDC_EDIT_SCH_DELAY_TIME         1061
#define IDC_BUTTON_SCH_OK               1062
#define IDC_BUTTON_SCH_CANCEL           1063
#define IDC_STATIC_DELAY_TIME           1064
#define IDC_LIST_LAND_GATE              1065
#define IDC_BUTTON_LAND_GATE_NEW        1066
#define IDC_BUTTON_LAND_GATE_EDIT       1067
#define IDC_BUTTON_LAND_GATE_DEL        1068
#define IDC_BUTTON_LAND_GATE_COPY       1069
#define IDC_CHECK_LAND_GATE_REND        1070
#define IDC_EDIT_LAND_GATE_NAME         1071
#define IDC_CHECK_LAND_GATE_OUT         1072
#define IDC_CHECK_LAND_GATE_IN          1073
#define IDC_EDIT_LAND_GATE_ID           1074
#define IDC_EDIT_LAND_GATE_TOMAP_MID    1075
#define IDC_EDIT_LAND_GATE_TOMAP_SID    1076
#define IDC_EDIT_LAND_GATE_TOGATE_ID    1077
#define IDC_EDIT_LAND_GATE_W            1078
#define IDC_EDIT_LAND_GATE_H            1079
#define IDC_BUTTON_LAND_GATE_APPLY      1080
#define IDC_BUTTON_LAND_GATE_REGIS      1081
#define IDC_STATIC_ATTRB                1082
#define IDC_STATIC_GATEID               1083
#define IDC_STATIC_TOMAP_ID             1084
#define IDC_STATIC_TOGATE_ID            1085
#define IDC_STATIC_GEN_INTER            1086
#define IDC_TREE_CROW                   1087
#define IDC_BUTTON_CROW_OK              1088
#define IDC_BUTTON_CROW_CANCEL          1089
#define IDC_CHECK_PENET_PARTY           1090
#define IDC_BUTTON_PENET_LEVEL          1091
#define IDC_EDIT_PENET_LEVEL_CON1       1092
#define IDC_COMBO_PENET_LEVEL_SIGN      1093
#define IDC_EDIT_PENET_LEVEL_CON2       1094
#define IDC_BUTTON_PENET_ITEM           1095
#define IDC_EDIT_PENET_ITEM_MID         1096
#define IDC_EDIT_PENET_ITEM_SID         1097
#define IDC_EDIT_PENET_ITEM_NAME        1098
#define IDC_BUTTON_PENET_ITEM_DEL       1099
#define IDC_BUTTON_PENET_SKILL          1100
#define IDC_EDIT_PENET_SKILL_MID        1101
#define IDC_EDIT_PENET_SKILL_SID        1102
#define IDC_EDIT_PENET_SKILL_NAME       1103
#define IDC_BUTTON_PENET_SKILL_DEL      1104
#define IDC_BUTTON_PENET_COMP_QUEST     1105
#define IDC_EDIT_PENET_COMP_QUEST_NAME  1106
#define IDC_BUTTON_PENET_COMP_QUEST_DEL 1107
#define IDC_BUTTON_PENET_PROG_QUEST     1108
#define IDC_EDIT_PENET_PROG_QUEST_NAME  1109
#define IDC_BUTTON_PENET_PROG_QUEST_DEL 1110
#define IDC_BUTTON_PENET_LP             1111
#define IDC_EDIT_PENET_LP_VAL           1112
#define IDC_BUTTON__PENET_LP_DEL        1113
#define IDC_COMBO_PENET_LP_SIGN         1114
#define IDC_BUTTON_PENET_ATTR           1115
#define IDC_EDIT_PENET_ATTR_VAL         1116
#define IDC_BUTTON_PENET_ATTR_DEL       1117
#define IDC_COMBO_PENET_ATTR_SIGN       1118
#define IDC_BUTTON_PENET_SAVE           1119
#define IDC_TREE_ITEM                   1120
#define IDC_BUTTON_ITEM_OK              1121
#define IDC_BUTTON_ITEM_CANCEL          1122
#define IDC_TREE_SKILL                  1123
#define IDC_BUTTON_SKILL_OK             1124
#define IDC_BUTTON_SKILL_CANCEL         1125
#define IDC_LIST_GATE                   1126
#define IDC_BUTTON_GATE_OK              1127
#define IDC_BUTTON_GATE_CANCEL          1128
#define IDC_BUTTON_SINGLE_EFF_NEW       1129
#define IDC_BUTTON_SINGLE_EFF_EDIT      1130
#define IDC_BUTTON_SINGLE_EFF_DEL       1131
#define IDC_EDIT_SINGLE_EFF_NAME        1132
#define IDC_EDIT_SINGLE_EFF_FNAME       1133
#define IDC_BUTTON_SINGLE_EFF_FIND      1134
#define IDC_BUTTON_SINGLE_EFF_APPLY     1135
#define IDC_BUTTON_SINGLE_EFF_REGIS     1136
#define IDC_LIST_SINGLE_EFF             1137
#define IDC_LIST_LAND_MARK              1138
#define IDC_BUTTON_LAND_MARK_NEW        1139
#define IDC_BUTTON_LAND_MARK_EDIT       1140
#define IDC_BUTTON_LAND_MARK_DEL        1141
#define IDC_EDIT_LAND_MARK_NAME         1142
#define IDC_BUTTON_LAND_MARK_REGIS      1143
#define IDC_CHECK_LIMIT_TIME_USE        1144
#define IDC_EDIT_LIMIT_TIME_MAX         1145
#define IDC_EDIT_LIMIT_TELL_TIME        1146
#define IDC_CHECK_CAM_USE               1147
#define IDC_EDIT_CAM_UP                 1148
#define IDC_EDIT_CAM_DOWN               1149
#define IDC_EDIT_CAM_LEFT               1150
#define IDC_EDIT_CAM_RIGHT              1151
#define IDC_BUTTON_CAM_SET_CENTER       1152
#define IDC_CHECK_CAM_TEST              1153
#define IDC_EDIT_CAM_FAR                1154
#define IDC_EDIT_CAM_X_VAL              1155
#define IDC_EDIT_CAM_Y_VAL              1156
#define IDC_EDIT_CAM_Z_VAL              1157
#define IDC_CHECK_ETC_FUNC_MON_CHASE    1158
#define IDC_CHECK_LAND_EFF_USE          1159
#define IDC_LIST_LAND_EFF               1160
#define IDC_COMBO_LAND_EFF              1161
#define IDC_EDIT_LAND_EFF_VAL           1162
#define IDC_BUTTON_LAND_EFF_ADD         1163
#define IDC_BUTTON_LAND_EFF_DEL         1164
#define IDC_BUTTON_ETC_FUNC_SAVE        1165
#define IDC_EDIT_CAM_NEAR               1166
#define IDC_BUTTON_QUEST_OK             1169
#define IDC_BUTTON_QUEST_CANCEL         1170
#define IDC_LIST_QUEST                  1171
#define ID_FILE_TOOLBAR_CAMTO           32771
#define ID_FILE_TOOLBAR_COMBOBOX        32773
#define ID_FILE_TOOLBAR_ALL90           32774
#define ID_FILE_TOOLBAR_SEP             32781
#define ID_VIEW_FIXCAMERATOCHARACTER    32784
#define ID_VIEW_MOVECHARACTERTOSELECTPOSITION 32789
#define ID_FILE_MENU_OPEN               32790
#define ID_FILE_MENU_SAVE               32791
#define ID_EDIT_MENU_NONE               32792
#define ID_EDIT_MENU_SELECT             32793
#define ID_EDIT_MENU_MOVE               32794
#define ID_EDIT_MENU_ROTATE             32795
#define ID_EDIT_MENU_SCALE              32796
#define ID_EDIT_MENU_EDITBOX            32797
#define ID_EDIT_MENU_SELECT_MOBSCH      32798
#define ID_VIEW_CONFIGURATIONDIALOG     32799

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32800
#define _APS_NEXT_CONTROL_VALUE         1172
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
