//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by [Tool]__MobEditor.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MOBEDIT_TREE                101
#define IDD_MOBEDIT_DIALOG              102
#define IDS_STRING102                   102
#define IDD_MOBEDITOR_DATAPAGE          103
#define IDD_MOBEDIT_DATA                103
#define IDD_MOBEDIT_ATTACK              104
#define IDR_MAINFRAME                   128
#define IDR_MENU_CROW                   129
#define IDC_BUTTON_LOAD                 1000
#define IDC_BUTTON_SAVE                 1001
#define IDC_BUTTON_SAVEOLD              1002
#define IDC_TREE_CROW                   1002
#define IDC_BUTTON_LOADCSV              1003
#define IDC_TEXT_BLOWLIFE               1003
#define IDC_BUTTON_SAVECSV              1004
#define IDC_BUTTON_CANCEL               1004
#define IDC_BUTTON_OK                   1005
#define IDC_BUTTON_NEXT                 1006
#define IDC_CROW_MID                    1007
#define IDC_CROW_SID                    1008
#define IDC_CROW_ID                     1010
#define IDC_CROW_NAME                   1011
#define IDC_COMBO_EMTRIBE               1012
#define IDC_COMBO_EMCROW                1013
#define IDC_COMBO_EMBRIGHT              1014
#define IDC_COMBO_PETTYPE               1015
#define IDC_EDIT_LEVEL                  1016
#define IDC_EDIT_HP                     1017
#define IDC_EDIT_MP                     1018
#define IDC_EDIT_SP                     1019
#define IDC_EDIT_HPREC                  1020
#define IDC_EDIT_MPREC                  1021
#define IDC_EDIT_SPREC                  1022
#define IDC_EDIT_GENTIME                1023
#define IDC_EDIT_AVOIDRATE              1024
#define IDC_EDIT_HITRATE                1025
#define IDC_EDIT_VIEWDISTANCE           1026
#define IDC_EDIT_DEFENSE                1027
#define IDC_EDIT_RES_FIRE               1028
#define IDC_EDIT_RES_ELECT              1029
#define IDC_EDIT_RES_SPIRIT             1030
#define IDC_EDIT_RES_ICE                1031
#define IDC_EDIT_RES_POISON             1032
#define IDC_EDIT_BONUSEXP               1033
#define IDC_EDIT_GATHERTIMELOW          1034
#define IDC_EDIT_GATHERTIMEHIGH         1035
#define IDC_EDIT_GATHERRATE             1036
#define IDC_COMBO_GATHERANIMATION       1037
#define IDC_CHECK_OVERLAPATTACK         1038
#define IDC_COMBO_ACTIONUP              1039
#define IDC_EDIT_BODYRADIUS             1040
#define IDC_EDIT_SKINFILE               1041
#define IDC_EDIT_CONVERSATIONFILE       1042
#define IDC_EDIT_SALE1                  1043
#define IDC_EDIT_SALE2                  1044
#define IDC_EDIT_SALE3                  1045
#define IDC_BUTTON_SKINFILE             1046
#define IDC_BUTTON_CONVERSATIONFILE     1047
#define IDC_BUTTON_SALE1                1048
#define IDC_BUTTON_SALE2                1049
#define IDC_BUTTON_SALE3                1050
#define IDC_EDIT_BIRTHEFFECT            1051
#define IDC_EDIT_DEATHEFFECT            1052
#define IDC_EDIT_HITEFFECT              1053
#define IDC_BUTTON_BIRTHEFFECT          1054
#define IDC_BUTTON_DEATHEFFECT          1055
#define IDC_BUTTON_HITEFFECT            1056
#define IDC_COMBO_ACTIONDN              1057
#define IDC_CHECK_AFTERFALL             1058
#define IDC_EDIT_ACTFLAG                1059
#define IDC_COMBO_MOVETYPE              1060
#define IDC_EDIT_FLOATING               1061
#define IDC_EDIT_WALKSPEED              1062
#define IDC_CHECK_RUN                   1063
#define IDC_EDIT_RUNSPEED               1064
#define IDC_EDIT_LIVETIME               1066
#define IDC_EDIT_ACTIONDNRATE           1067
#define IDC_CHECK_MOBLINK               1068
#define IDC_EDIT_MOBLINKMID             1069
#define IDC_EDIT_MOBLINKSID             1070
#define IDC_EDIT_MOBLINKSCALE           1071
#define IDC_EDIT_MOBLINKDELAY           1072
#define IDC_EDIT_PATTERNSIZE            1086
#define IDC_EDIT_GENMONEY               1094
#define IDC_EDIT_GENMONEY_RATE          1095
#define IDC_EDIT_GENITEM_MID            1096
#define IDC_EDIT_GENITEM_SID            1097
#define IDC_EDIT_GENITEM_RATE           1098
#define IDC_BUTTON_ITEMGEN              1099
#define IDC_BUTTON_ITEMGEN_Q            1100
#define IDC_EDIT_ITEMGEN                1101
#define IDC_EDIT_ITEMGEN_Q              1102
#define IDC_CHECK_EMCROWACT_TARSHORT    1103
#define IDC_CHECK_EMCROWACT_CDCERTIFY   1104
#define IDC_CHECK_EMCROWACT_INVISIBLE   1105
#define IDC_CHECK_EMCROWACT_RECVISIBLE  1106
#define IDC_CHECK_EMCROWACT_BARRIER     1107
#define IDC_CHECK_EMCROWACT_POSHOLD     1108
#define IDC_CHECK_EMCROWACT_DIRHOLD     1109
#define IDC_CHECK_EMCROWACT_KNOCK       1110
#define IDC_CHECK_EMCROWACT_BOSS        1111
#define IDC_CHECK_EMCROWACT_BUSUNIT     1112
#define IDC_CHECK_EMCROWACT_IGNORE_SHOCK 1113
#define IDC_CHECK_EMCROWACT_AUTODROP    1114
#define IDC_CHECK_EMCROWACT_SG          1115
#define IDC_CHECK_EMCROWACT_MP          1116
#define IDC_BUTTON_BACK                 1117
#define IDC_CHECK_EMCROWACT_PHX         1117
#define IDC_BUTTON_INDEXBACK            1118
#define IDC_CHECK_EMCROWACT_CONTROLLER  1118
#define IDC_BUTTON_INDEXNEXT            1119
#define IDC_CHECK_EMCROWACT_BUSUNIT3    1119
#define IDC_CHECK_EMCROWACT_SPECIAL     1119
#define IDC_EDIT_INDEX                  1120
#define IDC_CHECK_USED                  1121
#define IDC_COMBO_ATTACKRGTYPE          1122
#define IDC_EDIT_RANGE                  1123
#define IDC_EDIT_DAMAGE_LOW             1124
#define IDC_EDIT_DAMAGE_HIGH            1125
#define IDC_EDIT_DELAY                  1126
#define IDC_EDIT_SPUSAGE                1127
#define IDC_EDIT_SKILL_MID              1128
#define IDC_EDIT_SKILL_SID              1129
#define IDC_EDIT_SKILL_LEVEL            1130
#define IDC_COMBO_SKTAR                 1131
#define IDC_COMBO_TROUBLETYPE           1132
#define IDC_EDIT_BLOW_RATE              1133
#define IDC_EDIT_BLOW_LIFE              1134
#define IDC_EDIT_BLOW_VAR1              1135
#define IDC_EDIT_BLOW_VAR2              1136
#define IDC_BUTTON_SELFBODYEFFECT       1137
#define IDC_EDIT_SELFBODYEFFECT         1138
#define IDC_EDIT_TARGETBODYEFFECT       1139
#define IDC_EDIT_TARGETEFFECT           1140
#define IDC_BUTTON_TARGETBODYEFFECT     1141
#define IDC_BUTTON_TARGETEFFECT         1142
#define IDC_TEXT_BLOWRATE               1143
#define IDC_TEXT_BLOWVAR2               1144
#define IDC_TEXT_BLOWVAR1               1145
#define IDC_EDIT_DAMAGE_LOW2            1146
#define IDC_LIST_PATTERN                1146
#define IDC_EDIT_DAMAGE_HIGH2           1147
#define IDC_BUTTON_PATTERNEDIT          1148
#define IDC_EDIT_PATTERNDNRATE          1149
#define IDC_COMBO_ACTPATTERN            1150
#define IDC_EDIT_PATTERNATTACKSET       1151
#define IDC_BUTTON_PATTERNOK            1152
#define IDC_BUTTON_PATTERNADD           1153
#define IDC_BUTTON_PATTERNDELETE        1154
#define IDC_LIST_ANI                    1155
#define IDC_EDIT_ANINAME                1156
#define IDC_EDIT_ANISTIME               1158
#define IDC_EDIT_ANIETIME               1159
#define IDC_EDIT_ANIUNITTIME            1160
#define IDC_EDIT_FLAGS                  1161
#define IDC_COMBO_ANIMID                1162
#define IDC_COMBO_ANISID                1163
#define IDC_EDIT_ANIDIVCOUNT            1164
#define IDC_LIST_ANIDIV                 1165
#define IDC_BUTTON_ANIUSE               1166
#define IDC_EDIT_SCHOOLREQ              1172
#define IDC_STATIC_BASE                 1174
#define ID_Menu                         32778
#define ID_MENU_ADD                     32780
#define ID_MENU_COPY                    32781
#define ID_MENU_DELETE                  32782
#define ID_MENU_PASTENEW                32783
#define ID_MENU_PASTEVALUE              32784
#define ID_MENU_CROWDATAEDIT            32785
#define ID_MENU_CROWATTACKEDIT          32786
#define ID_MENU_JDEV                    32787

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32788
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
