//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NpcAction.rc
//
#define ID_BUTTON_FIND                  3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_NPCACTION_DIALOG            102
#define IDS_PROPSHT_CAPTION             102
#define IDD_NPCACTIONPAGE               103
#define IDD_NPCACTIONTABLE              104
#define IDD_NPCACTIONCONDITION          105
#define IDD_NPCACTIONANSWER             106
#define IDD_NPCTALKDIALOG               107
#define IDD_HAVEITEMDIALOG              109
#define IDD_LEARNSKILLDIALOG            110
#define IDD_FINDITEM                    111
#define IDD_DLGNPCTALK                  112
#define IDR_MAINFRAME                   128
#define ID_MENUITEM_NEW                 131
#define IDR_MENU1                       131
#define ID_MENUITEM_LOAD                132
#define IDD_DIALOG_QUEST                132
#define IDR_MENU2                       132
#define ID_MENUITEM_SAVE                133
#define IDD_SIMPLEEDIT                  134
#define IDD_NPCACTION_DIALOG2           136
#define IDD_NPCACTIONCONDITION5         139
#define IDD_FINDITEM5                   139
#define IDR_TOOLBAR1                    145
#define IDD_SIMPLEEDIT1                 145
#define IDC_STATIC_CONTROL              1004
#define IDC_LIST_ACTION                 1006
#define IDC_EDIT_DIALOGUE_TALK          1007
#define IDC_EDIT_DIALOGUE_CONDITION     1007
#define IDC_EDIT_DIALOGUE_TALK2         1008
#define IDC_EDIT_DIALOGUE_TALK_NEGATIVE 1008
#define IDC_EDIT_DIALOGUE_BASIC_TALK    1008
#define IDC_BUTTON_CANCEL               1013
#define IDC_BUTTON_OK                   1015
#define IDC_BUTTON_INSERT               1016
#define IDC_BUTTON_MODIFY               1017
#define IDC_BUTTON_DELETE               1018
#define IDC_EDIT_DIALOGUE_ID            1019
#define IDC_BUTTON_TEST                 1019
#define IDC_BUTTON_CONDITION            1026
#define IDC_BUTTON_POSTIVE_ANSWER       1027
#define IDC_BUTTON_NEGATIVE_ANSWER      1028
#define IDC_BUTTON_CASE_NEW             1028
#define IDC_BUTTON_POSTIVE_ANSWER_DEL   1029
#define IDC_EDIT_CONDITION              1030
#define IDC_BUTTON_NEGATIVE_ANSWER_DEL  1031
#define IDC_BUTTON_CASE_EDIT            1031
#define IDC_LIST_POSTIVE_ANSWER         1032
#define IDC_LIST_CASE_ANSWER            1032
#define IDC_LIST_NEGATIVE_ANSWER        1033
#define IDC_BUTTON_DEL                  1033
#define IDC_BUTTON_CASE_DEL             1033
#define IDC_LIST_ANSWER                 1034
#define IDC_BUTTON_CONDITION_DEL        1034
#define IDC_LIST_POSTIVE_ANSWER2        1034
#define IDC_BUTTON_ADD                  1035
#define IDC_BUTTON_CASE_COPY            1035
#define IDC_STATIC_TYPE                 1036
#define IDC_EDIT_TALK                   1037
#define IDC_BUTTON_DELALL               1037
#define IDC_COMBO_ACTION_TYPE           1038
#define IDC_COMBO_ACTION_DATA           1039
#define IDC_EDIT_TALKID                 1040
#define IDC_COMBO_QUEST_PROG            1041
#define IDC_CHECK_LEVEL                 1042
#define IDC_COMBO_QUEST_PROG_STEP       1042
#define IDC_COMBO_QUEST_START           1043
#define IDC_CHECK_CLASS                 1044
#define IDC_COMBO_QUEST_START2          1044
#define IDC_CHECK_ELEMENTAL             1045
#define IDC_COMBO_QUEST_START3          1045
#define IDC_COMBO_QUEST_START4          1046
#define IDC_COMBO_QUEST_START5          1047
#define IDC_EDIT_LEVEL                  1052
#define IDC_EDIT_ELEMENTAL              1053
#define IDC_COMBO_LEVEL_SIGN            1054
#define IDC_CHECK_FIGHETER              1055
#define IDC_CHECK_SPIRIT                1056
#define IDC_CHECK_ARCHER                1057
#define IDC_EDIT_MONEY                  1058
#define IDC_BUTTON_ITEM_ADD             1059
#define IDC_LIST_ITEM                   1060
#define IDC_BUTTON_ITEM_DEL             1061
#define IDC_BUTTON_SKILL_DEL            1062
#define IDC_BUTTON_ITEM_DELALL          1063
#define IDC_BUTTON_SKILL_DELALL         1064
#define IDC_CHECK_ARMS                  1065
#define IDC_COMBO_ELEMENTAL_SIGN        1066
#define IDC_CHECK_ACTIONPOINT           1067
#define IDC_COMBO_SKILL_LEVEL           1067
#define IDC_BUTTON_ITEM_QUEST_SELECT    1067
#define IDC_EDIT_ACTIONPOINT            1068
#define IDC_EDIT_DIALOGUE_TALK_POSTIVE  1068
#define IDC_EDIT_DIALOGUE_CASE          1068
#define IDC_COMBO_ACTIONPOINT_SIGN      1069
#define IDC_EDIT1                       1069
#define IDC_EDIT_PAGENUM                1069
#define IDC_EDIT_DIALOGUE_CASE_CONDITION 1069
#define IDC_EDIT_HAVE_ITEM              1069
#define IDC_BASICCONV_EDIT              1069
#define IDC_CHECK_TIME                  1070
#define IDC_EDIT_TRADE_ITEM             1070
#define IDC_EDIT2                       1070
#define IDC_EDIT_QUEST                  1071
#define IDC_BASICCONV_EDIT2             1071
#define IDC_EDIT_HAVE_ITEM2             1071
#define IDC_COMBO_TIME_BEGIN            1072
#define IDC_BUTTON_CONDITON_EDIT        1072
#define IDC_EDIT_HAVE_ITEM3             1072
#define IDC_COMBO_TIME_END              1073
#define IDC_BUTTON_CONDITON_DEL         1073
#define IDC_BUTTON_CONDITON_SET         1073
#define IDC_CHECK_QUEST                 1074
#define IDC_COMBO_QUEST_STEP            1074
#define IDC_BUTTON_CONDITON_RESET       1074
#define IDC_BUTTON_HAVE_ITEM            1075
#define IDC_BUTTON_DIS_SKILL_DEL        1075
#define IDC_BUTTON_TRADE_ITEM           1076
#define IDC_BUTTON_DIS_QUEST_DEL        1076
#define IDC_BUTTON_HAVE_DEL             1077
#define IDC_BUTTON_COMQUEST_DEL         1077
#define IDC_BUTTON_TRADE_DEL            1078
#define IDC_EDIT_PARTY                  1078
#define IDC_BUTTON_SKILL_ADD            1079
#define IDC_EDIT_HAVE_ITEM4             1079
#define IDC_LIST_SKILL                  1080
#define IDC_EDIT_HAVE_ITEM5             1080
#define IDC_CHECK_ITEM                  1081
#define IDC_BUTTON_DIS_SKILL_ADD        1081
#define IDC_CHECK_SKILL                 1082
#define IDC_LIST_DIS_SKILL              1082
#define IDC_BUTTON_DIS_QUEST_ADD        1083
#define IDC_LIST_DIS_QUEST              1084
#define IDC_BUTTON_QUEST_DEL            1085
#define IDC_LIST1                       1086
#define IDC_BUTTON_COMQUEST_ADD         1086
#define IDC_STATIC_QUEST_START          1087
#define IDC_LIST_COMQUEST               1087
#define IDC_STATIC_QUEST_STEP           1088
#define IDC_BUTTON_UP                   1088
#define IDC_BUTTON_COMQUEST_DELALL      1088
#define IDC_STATIC_QUEST_STEP2          1089
#define IDC_BUTTON_DOWN                 1089
#define IDC_COMBO_SCHOOL                1089
#define IDC_BUTTON1                     1090
#define IDC_BUTTON_COPY                 1090
#define IDC_STATIC_QUEST_STEP3          1090
#define IDC_CSV_SAVE_BUTTON             1090
#define IDC_BUTTON_FIND                 1090
#define IDC_EDIT_BUS                    1091
#define IDC_CHECK_EXTREME_W             1091
#define IDC_ANSWERAPPLY_BUTTON          1091
#define IDC_CSV_SAVE_BUTTON2            1091
#define IDC_BUTTON2                     1092
#define IDC_BUTTON_BUS                  1092
#define IDC_TEXTAPPLY_BUTTON            1092
#define IDC_TEXTEXPORT_BUTTON           1092
#define IDC_CHECK_FIGHETER_W            1092
#define IDC_CHECK_EXTREME_M             1093
#define IDC_TEXTIMPORT_BUTTON           1093
#define IDC_CHECK_ALL                   1094
#define IDC_CSVEXPORT_BUTTON            1094
#define IDC_CHECK_SPIRIT_M              1095
#define IDC_CSVEXPORT_BUTTON2           1095
#define IDC_CHECK_ARCHER_M              1096
#define IDC_CHECK_ARMS_W                1097
#define IDC_BASIC_SLIDER                1099
#define IDC_BASIC_EDIT                  1100
#define IDC_TEXT_SLIDER                 1101
#define IDC_TEXT_EDIT                   1102
#define IDC_ANSWER_LIST                 1115
#define IDC_ANSWERID_EDIT               1116
#define IDC_ANSWER_EDIT                 1117
#define IDC_ANSWERTYPE_EDIT             1118
#define IDC_ANSWERDATA_EDIT             1119
#define IDC_CSVIMPORT_BUTTON            1125
#define IDC_CHECK_FIGHETER_M            1126
#define IDC_ALLSAVE_BUTTON              1126
#define IDC_CHECK_ARMS_M                1127
#define IDC_CSVIMPORT_BUTTON2           1127
#define IDC_CHECK_ARCHER_W              1128
#define IDC_CHECK_SPIRIT_W              1129
#define IDC_LISTCONT_ITEM               1131
#define IDC_EDIT_HAVE_ITEM1             1132
#define IDD_DIALOG1                     1133
#define IDC_CHECK_QUEST_START2          1133
#define IDC_CHECK_QUEST_START3          1134
#define IDC_CHECK_QUEST_START4          1135
#define IDC_CHECK_QUEST_START5          1136
#define IDC_LIST_CASE_RANDOM            1137
#define IDC_EDIT_RANDOM_TIME            1138
#define IDC_RANDOM_INSERT               1139
#define IDC_RANDOM_DELETE               1140
#define IDC_RANDOM_RESET                1141
#define IDC_RANDOM_STATIC               1142
#define IDC_TIME_STATIC                 1143
#define IDC_NPCTALK_LIST                1144
#define IDC_RADIO_ALL                   1145
#define IDC_RADIO_MAN                   1146
#define IDC_EDIT_FINDMID                1146
#define IDC_EDIT_FINDID                 1146
#define IDC_EDIT_FINDSID                1147
#define IDC_EDIT_FINDMID2               1147
#define IDC_RADIO_WOMAN                 1147
#define IDD_NPCSIMPLEEDIT               1333
#define ID_MENUITEM_EXIT                32775
#define ID_FILE_ALLTEXTEXPORT           32776
#define ID_FILE_ALLTEXTEXPORT2          32777

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1147
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
