#pragma once

namespace SUBPATH
{
	extern TCHAR APP_ROOT[MAX_PATH];

	extern TCHAR SAVE_ROOT[MAX_PATH];

	extern TCHAR PLAYINFO_ROOT[MAX_PATH];
	extern TCHAR DEBUGINFO_ROOT[MAX_PATH];
	extern TCHAR CAPTURE[MAX_PATH];
	extern TCHAR CHATLOG[MAX_PATH];

	extern TCHAR CACHE[MAX_PATH];

	extern TCHAR OBJ_FILE_ROOT[MAX_PATH];
	extern TCHAR OBJ_FILE_EDIT[MAX_PATH];
	extern TCHAR OBJ_FILE_PIECE[MAX_PATH];
	extern TCHAR OBJ_FILE_PIECEEDIT[MAX_PATH];
	extern TCHAR OBJ_FILE_SKIN[MAX_PATH];
	extern TCHAR OBJ_FILE_SKELETON[MAX_PATH];
	extern TCHAR OBJ_FILE_ANIMATION[MAX_PATH];
	extern TCHAR OBJ_FILE_SKINOBJECT[MAX_PATH];

	extern TCHAR MAP_FILE[MAX_PATH];
	extern TCHAR GLMAP_FILE[MAX_PATH];
	extern TCHAR GLOGIC_FILE[MAX_PATH];
	extern TCHAR GLOGIC_SERVER_FILE[MAX_PATH];

	extern TCHAR TILE_FILE_DATA[MAX_PATH];
	extern TCHAR TILE_FILE_TEXTURE[MAX_PATH];

	extern TCHAR OBJ_FILE_OBJECT[MAX_PATH];
	extern TCHAR OBJ_FILE_STATICMESH[MAX_PATH];

	extern TCHAR TEXTURE_FILE_ROOT[MAX_PATH];
	extern TCHAR TEXTURE_FILE_SHADOW[MAX_PATH];
	extern TCHAR TEXTURE_FILE_CLUB[MAX_PATH];
	extern TCHAR TEXTURE_FILE_EFF[MAX_PATH];
	extern TCHAR SHADER_FILE_ROOT[MAX_PATH];

	extern TCHAR EFF_FILE_SINGLE[MAX_PATH];
	extern TCHAR EFF_FILE_CHAR[MAX_PATH];

	extern TCHAR	SOUND_FILE_ROOT[MAX_PATH];
	extern TCHAR BGM_FILE_ROOT[MAX_PATH];

	extern TCHAR GUI_FILE_ROOT[MAX_PATH];
	extern TCHAR NTK_FILE_ROOT[MAX_PATH];
	extern TCHAR QST_FILE_ROOT[MAX_PATH];
};
