//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SkillEditor.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SKILLEDITOR_TREEPAGE        101
#define IDD_SKILLEDITOR_DIALOG          102
#define IDS_PROPSHT_CAPTION             102
#define IDD_SKILLEDITOR_BASIC           103
#define IDD_SKILLEDITOR_LEVEL           104
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       129
#define IDC_STATIC_CONTROL              1000
#define IDC_BUTTON_LOADSKILL            1001
#define IDC_TREE_SKILL                  1002
#define IDC_BUTTON_SAVE                 1002
#define IDC_BUTTON_OK                   1002
#define IDC_BUTTON_LOADCSV              1003
#define IDC_BUTTON_CANCEL               1003
#define IDC_BUTTON_SAVECSV              1004
#define IDC_EDIT_SMID                   1004
#define IDC_EDIT_SSID                   1005
#define IDC_BUTTON_SAVE2                1005
#define IDC_EDIT_SNAME                  1006
#define IDC_BUTTON_SAVE3                1006
#define IDC_EDIT_SDESC                  1007
#define IDC_BUTTON_LOADCSV2             1007
#define IDC_EDIT_ENAME                  1008
#define IDC_EDIT_EDESC                  1009
#define IDC_EDIT_BGRADE                 1010
#define IDC_EDIT_BMASTERLEVEL           1011
#define IDC_COMBO_EMROLE                1012
#define IDC_COMBO_EMAPPLY               1013
#define IDC_COMBO_EMIMPACTTAR           1014
#define IDC_COMBO_EMIMPACTREALM         1015
#define IDC_COMBO_EMIMPACTSIDE          1016
#define IDC_EDIT_BRANGE                 1017
#define IDC_COMBO_EEMUSELITEM           1018
#define IDC_COMBO_EEMUSERITEM           1019
#define IDC_COMBO_EMBASICTYPE           1020
#define IDC_COMBO_EMELEMENT             1021
#define IDC_COMBO_EMSTATEBLOW           1022
#define IDC_COMBO_EMADDON               1023
#define IDC_COMBO_EMSPEC                1024
#define IDC_COMBO_EMSSTYPE              1025
#define IDC_BUTTON_ELEMINUS             1026
#define IDC_EDIT_ELEMTYPE               1027
#define IDC_BUTTON_ELEADD               1028
#define IDC_BUTTON_TAR01                1029
#define IDC_EDIT_TAR01                  1030
#define IDC_COMBO_TAR01                 1031
#define IDC_COMBO_TARP01                1032
#define IDC_BUTTON_TAR02                1033
#define IDC_EDIT_TAR02                  1034
#define IDC_COMBO_TAR02                 1035
#define IDC_COMBO_TARP02                1036
#define IDC_BUTTON_SELF01               1037
#define IDC_EDIT_SELF01                 1038
#define IDC_COMBO_SELF01                1039
#define IDC_COMBO_SELFP01               1040
#define IDC_BUTTON_SELF02               1041
#define IDC_EDIT_SELF02                 1042
#define IDC_COMBO_SELF02                1043
#define IDC_COMBO_SELFP02               1044
#define IDC_BUTTON_TAR                  1045
#define IDC_EDIT_TAR                    1046
#define IDC_COMBO_TAR                   1047
#define IDC_COMBO_TARPA                 1048
#define IDC_COMBO_TARPB                 1049
#define IDC_BUTTON_SELFBODY             1050
#define IDC_CHECK_SINGLEEFFECT          1051
#define IDC_EDIT_SELFBODY               1052
#define IDC_COMBO_SELFBODY              1053
#define IDC_BUTTON_TARGETBODY1          1054
#define IDC_EDIT_TARGETBODY1            1055
#define IDC_EDIT_TARGETBODY2            1056
#define IDC_BUTTON_TARGETBODY2          1057
#define IDC_COMBO_TARGETBODY1           1058
#define IDC_COMBO_TARGETBODY2           1059
#define IDC_BUTTON_TARGETBODY3          1060
#define IDC_COMBO_EMBRIGHT              1061
#define IDC_EDIT_DAMAGEHOLD             1062
#define IDC_COMBO_EMANIMID              1063
#define IDC_COMBO_EMANISID              1064
#define IDC_BUTTON_ICON                 1065
#define IDC_EDIT_ICON                   1066
#define IDC_EDIT_ICON_X                 1067
#define IDC_EDIT_ICON_Y                 1068
#define IDC_EDIT_HOLDOUT                1069
#define IDC_CHECK_GM                    1070
#define IDC_EDIT_REQSKILLMID            1071
#define IDC_EDIT_REQSKILLSID            1072
#define IDC_EDIT_ANIMID                 1073
#define IDC_EDIT_ANISID                 1074
#define IDC_CHECK_CURE_PARALYSIS        1075
#define IDC_CHECK_CURE_POISON           1076
#define IDC_EDIT_SKILLLEVEL             1076
#define IDC_CHECK_CURE_FAINT            1077
#define IDC_BUTTON_LVLMINUS             1077
#define IDC_CHECK_CURE_FREEZE           1078
#define IDC_BUTTON_LVLADD               1078
#define IDC_CHECK_CURE_STONE            1079
#define IDC_STATIC_BASIC                1079
#define IDC_CHECK_CURE_MADNESS          1080
#define IDC_EDIT_BDELAY                 1080
#define IDC_CHECK_CURE_FLAME            1081
#define IDC_EDIT_BLIFE                  1081
#define IDC_CHECK_CURE_CURSE            1082
#define IDC_EDIT_BAPPLYRANGE            1082
#define IDC_BUTTON_NEXT                 1083
#define IDC_EDIT_BAPPLYNUM              1084
#define IDC_EDIT_BAPPLYANGLE            1085
#define IDC_EDIT_BPIERCENUM             1086
#define IDC_EDIT_BTARNUM                1087
#define IDC_EDIT_BBASICVAR              1088
#define IDC_EDIT_CHP                    1089
#define IDC_EDIT_CMP                    1090
#define IDC_EDIT_CSP                    1091
#define IDC_EDIT_CCP                    1092
#define IDC_EDIT_CEXP                   1093
#define IDC_EDIT_CARROW                 1094
#define IDC_EDIT_CCHARM                 1095
#define IDC_EDIT_CBULLET                1096
#define IDC_EDIT_CEXTRA                 1097
#define IDC_EDIT_CPHP                   1098
#define IDC_EDIT_CPMP                   1099
#define IDC_EDIT_CPSP                   1100
#define IDC_EDIT_RLEVEL                 1101
#define IDC_EDIT_RSKP                   1102
#define IDC_EDIT_RSKLEVEL               1103
#define IDC_EDIT_RREBORN                1104
#define IDC_EDIT_RPOW                   1105
#define IDC_EDIT_RSPR                   1106
#define IDC_EDIT_RINT                   1107
#define IDC_EDIT_RSTR                   1108
#define IDC_EDIT_RDEX                   1109
#define IDC_EDIT_RSTA                   1110
#define IDC_STATIC_STT                  1111
#define IDC_EDIT_STTRATE                1112
#define IDC_EDIT_STTVAR1                1113
#define IDC_EDIT_STTVAR2                1114
#define IDC_STATIC_TXTVAR1              1115
#define IDC_STATIC_TXTVAR2              1116
#define IDC_STATIC_SDE                  1117
#define IDC_EDIT_ADDONVAR               1118
#define IDC_STATIC_SPA                  1119
#define IDC_EDIT_SPVAR1                 1120
#define IDC_EDIT_SPVAR2                 1121
#define IDC_STATIC_SPVAR1               1122
#define IDC_STATIC_SPVAR2               1123
#define IDC_CHECK_TC_PARALYSIS          1124
#define IDC_CHECK_TC_FAINT              1125
#define IDC_CHECK_TC_STONE              1126
#define IDC_CHECK_TC_FLAME              1127
#define IDC_CHECK_TC_POISON             1128
#define IDC_CHECK_TC_FREEZE             1129
#define IDC_CHECK_TC_CURSE              1130
#define IDC_CHECK_TC_MADNESS            1131
#define IDC_EDIT_AS_MID                 1132
#define IDC_EDIT_AS_SID                 1133
#define IDC_EDIT_AS_LVL                 1134
#define IDC_STATIC_SPA2                 1135
#define IDC_EDIT_SUMMID                 1136
#define IDC_EDIT_SUMSID                 1137
#define IDC_EDIT_SUMTIME                1138
#define IDC_SCROLLBAR2                  1138
#define IDC_STATIC_SPA3                 1139
#define IDC_EDIT_REQMONEY               1140
#define IDC_EDIT_REQVOTEP               1141
#define IDC_EDIT_REQPREMP               1142
#define IDC_BUTTON_TRAN_M1              1143
#define IDC_BUTTON_TRAN_M2              1144
#define IDC_STATIC_SPA4                 1145
#define IDC_BUTTON_TRAN_M3              1160
#define IDC_BUTTON_TRAN_M4              1161
#define IDC_EDIT_TRANEFFECT             1164
#define IDC_BUTTON_TRANEFFECT           1165
#define IDC_EDIT_TRANEFFECTTIME         1166
#define IDC_BUTTON_TRAN_M5              1167
#define IDC_EDIT_TRAN_M1                1168
#define IDC_BUTTON_TRAN_M6              1169
#define IDC_BUTTON_TRAN_M7              1170
#define IDC_BUTTON_TRAN_M8              1171
#define IDC_BUTTON_TRAN_W1              1172
#define IDC_BUTTON_TRAN_W2              1173
#define IDC_BUTTON_TRAN_W3              1174
#define IDC_BUTTON_TRAN_W4              1175
#define IDC_EDIT_TRAN_M2                1176
#define IDC_EDIT_TRAN_M3                1177
#define IDC_EDIT_TRAN_M4                1178
#define IDC_EDIT_TRAN_M5                1179
#define IDC_EDIT_TRAN_M6                1180
#define IDC_EDIT_TRAN_M7                1181
#define IDC_EDIT_TRAN_M8                1182
#define IDC_EDIT_TRAN_W1                1183
#define IDC_EDIT_TRAN_W2                1184
#define IDC_EDIT_TRAN_W3                1185
#define IDC_EDIT_TRAN_W4                1186
#define IDC_EDIT_TRAN_W5                1187
#define IDC_EDIT_TRAN_W6                1188
#define IDC_EDIT_TRAN_W7                1189
#define IDC_EDIT_TRAN_W8                1190
#define IDC_BUTTON_TRAN_W5              1191
#define IDC_BUTTON_TRAN_W6              1192
#define IDC_BUTTON_TRAN_W7              1193
#define IDC_BUTTON_TRAN_W8              1194
#define IDC_BUTTON_TRAN_CHF             1195
#define IDC_EDIT_TRAN_M9                1196
#define IDC_EDIT_TRAN_CHF               1196
#define ID_MENU_ADD                     32771
#define ID_MENU_DELETE                  32772
#define ID_MENU_COPY                    32773
#define ID_MENU_PASTENEW                32776
#define ID_MENU_PASTEVALUE              32777
#define ID_MENU_SKILLDATAEDIT           32780
#define ID_MENU_SKILLLEVELEDIT          32781
#define ID_MENU_JDEV                    32783

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32784
#define _APS_NEXT_CONTROL_VALUE         1139
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
