//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by [Tool]__QuestEditor.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_QUESTEDIT_DIALOG            102
#define IDS_PROPSHT_CAPTION             102
#define IDD_FORMVIEW_QUEST              103
#define IDD_FORMVIEW_QUESTSTEP          104
#define IDD_INPUTIDDLG                  105
#define IDR_MAINFRAME                   128
#define IDR_MENU_MAINFRAME              130
#define IDD_DIALOG_NPC                  130
#define ID_MENUITEM_NEW                 131
#define IDD_DIALOG_ITEM                 131
#define ID_MENUITEM_LOAD                132
#define IDD_DIALOG_SKILL                132
#define ID_MENUITEM_SAVE                133
#define IDD_DIALOG_MAP                  133
#define ID_MENUITEM_EXIT                134
#define IDD_QUESTTREE_DIALOG            135
#define IDR_MENU_QUEST_POPUP            136
#define IDR_MENU_QUEST_POPU             137
#define IDR_MENU_QUEST_POPUP1           138
#define IDD_DLG_INVEN_ELEMENT_EDIT      140
#define IDD_DIALOG_MOBGEN_ITEM          141
#define IDD_DIALOG_MAP_SELELCT          142
#define ID_MENUITEM_ADD                 143
#define ID_MENUITEM_DEL                 144
#define IDR_TOOLBAR1                    145
#define IDD_FORMVIEW_QUEST5             146
#define IDD_QUESTTREE_DIALOG1           153
#define IDC_STATIC_CONTROL              1001
#define IDC_TREE_ITEM                   1002
#define IDC_EDIT_QUEST_NID              1006
#define IDC_EDIT_TALKNPC_NAME           1007
#define IDC_EDIT_QUEST_FILENAME         1007
#define IDC_EDIT_DIEMOB_NAME            1008
#define IDC_EDIT_GUARDNPC_NAME          1009
#define IDC_EDIT_MID                    1009
#define IDC_EDIT_DIEMOB_NUM             1010
#define IDC_EDIT_NAME                   1010
#define IDC_CHECK_LIMIT_NONDIE          1011
#define IDC_EDIT_REACH_MAP_NAME         1011
#define IDC_EDIT_FIRE                   1011
#define IDC_CHECK_REPEAT                1012
#define IDC_EDIT_REACH_PX               1012
#define IDC_LIST_STEP                   1013
#define IDC_EDIT_ICE                    1013
#define IDC_CHECK_AGAIN                 1014
#define IDC_EDIT_REACH_PY               1014
#define IDC_EDIT_ELECTRIC               1014
#define IDC_EDIT_BEGIN_PARTYNUM         1015
#define IDC_EDIT_REACH_RADIUS           1015
#define IDC_EDIT_DEFENSE                1016
#define IDC_CHECK_PARTY                 1017
#define IDC_EDIT_GUARD_MAP_NAME         1017
#define IDC_EDIT_POISON                 1017
#define IDC_CHECK_ONLYONE_PROG          1018
#define IDC_EDIT_GUARD_PX               1018
#define IDC_EDIT_DAMAGE                 1018
#define IDC_CHECK_GIVEUP                1019
#define IDC_EDIT_GUARD_PY               1019
#define IDC_EDIT_SID                    1019
#define IDC_BUTTON_TALKNPC              1020
#define IDC_CHECK_PARTYQUEST            1020
#define IDC_EDIT_GIFT_EXP               1021
#define IDC_BUTTON_DIEMOB               1021
#define IDC_EDIT_TURNNUM                1021
#define IDC_EDIT_GIFT_MONEY             1022
#define IDC_BUTTON_GUARDNPC             1022
#define IDC_EDIT_SPIRIT                 1022
#define IDC_EDIT_GIFT_ELEMENT           1023
#define IDC_BUTTON_REACH_MAP            1023
#define IDC_EDIT_GIFT_LIFEP             1024
#define IDC_BUTTON_GUARD_MAP            1024
#define IDC_EDIT_GIFT_DISPK             1025
#define IDC_EDIT_GUARD_RADIUS           1025
#define IDC_EDIT_GIFT_QUEST             1026
#define IDC_EDIT_GIFT_STATP             1027
#define IDC_EDIT_GUARD_TIME             1027
#define IDC_BUTTON_REQ_QITEM_NEW        1028
#define IDC_BUTTON_REQ_QITEM_DEL        1029
#define IDC_BUTTON_NEXT                 1030
#define IDC_EDIT_STEP_COMMENT           1031
#define IDC_LIST_REQ_QITEM              1032
#define IDC_BUTTON_GIFT_SKILL_NEW       1033
#define IDC_BUTTON_STEP_NEW             1033
#define IDC_BUTTON_GIFT_SKILL_DEL       1034
#define IDC_BUTTON_REQ_STEP_DEL         1034
#define IDC_LIST_DEL_QITEM              1035
#define IDC_BUTTON_DEL_QITEM_NEW        1036
#define IDC_EDIT_TITLE                  1037
#define IDC_BUTTON_DEL_QITEM_DEL        1037
#define IDC_EDIT_COMMENT                1038
#define IDC_BUTTON_REQ_QITEM_EDIT       1038
#define IDC_EDIT_BEGIN_MONEY            1039
#define IDC_EDIT_TALKNPC_COMMENT        1039
#define IDC_EDIT_GIFT_SKILLP            1040
#define IDC_BUTTON_GIFT_QITEM_EDIT      1040
#define IDC_LIST_GIFT_ITEM              1041
#define IDC_EDIT_DIEMOB_COMMENT         1041
#define IDC_LIST_GIFT_SKILL             1042
#define IDC_EDIT_GUARDNPC_COMMENT       1042
#define IDC_BUTTON_GIFT_ITEM_NEW        1043
#define IDC_LIST_GIFT_QITEM             1043
#define IDC_BUTTON_GIFT_ITEM_DEL        1044
#define IDC_BUTTON_GIFT_QITEM_NEW       1044
#define IDC_BUTTON_GIFT_ITEM_EDIT       1045
#define IDC_BUTTON_GIFT_QITEM_DEL       1045
#define IDC_EDIT_LIMIT_PARTYNUM         1046
#define IDC_EDIT_REACH_MAP_COMMENT      1046
#define IDC_EDIT_LIMIT_TIME             1047
#define IDC_EDIT_GUARD_MAP_COMMENT      1047
#define IDC_BUTTON_PREV                 1048
#define IDC_EDIT_REQ_QITEM_COMMENT      1049
#define IDC_LIST_NPC                    1051
#define IDC_BUTTON_EDITCOMPLATE         1051
#define IDC_LIST_ITEM                   1052
#define IDC_LIST_MAP                    1053
#define IDC_LIST_SKILL                  1054
#define IDC_BUTTON_TALKNPC_DEL          1055
#define IDC_CHECK_FIGHETER              1055
#define IDC_BUTTON_DIEMOB_DEL           1056
#define IDC_CHECK_SPIRIT                1056
#define IDC_BUTTON_GUARDNPC_DEL         1057
#define IDC_CHECK_ARCHER                1057
#define IDC_BUTTON_REACH_MAP_DEL        1058
#define IDC_CHECK_FIGHETER_W            1058
#define IDC_BUTTON_GUARD_MAP_DEL        1059
#define IDC_CHECK_EXTREME_W             1059
#define IDC_STATIC_COMMENT              1060
#define IDC_CHECK_ARCHER_W              1060
#define IDC_STATIC_REQ_QITEM            1061
#define IDC_CHECK_SPIRIT_W              1061
#define IDC_STATIC_RESET_QITEM          1062
#define IDC_CHECK_EXTREME_W2            1062
#define IDC_CHECK_SCIENCE_W2            1062
#define IDC_CHECK_SCIENCE_W             1062
#define IDC_STATIC_REACH                1063
#define IDC_STATIC_COMMENT2             1064
#define IDC_CHECK_ARMS                  1065
#define IDC_STATIC_DEFENSE              1066
#define IDC_CHECK_ARMS_W                1066
#define IDC_STATIC_REACH_R              1067
#define IDC_STATIC_DEFENSE_R            1068
#define IDC_STATIC_DEFENSE_T            1069
#define IDC_BUTTON_STEP_OK              1070
#define IDC_EDIT_GEN_NUM                1071
#define IDC_STATIC_GIFT_QITEM           1072
#define IDC_EDIT_GEN_RATE               1072
#define IDC_BUTTON_GEN_MOB_ADD          1073
#define IDC_BUTTON_GEN_MOB_DEL          1075
#define IDC_LIST_GEN_MOB                1076
#define IDC_BUTTON_GENITEM              1077
#define IDC_EDIT_GENITEM                1078
#define IDC_EDIT_EDITVERSION            1079
#define IDC_EDIT_STEP_TITLE             1080
#define IDC_BUTTON_UP                   1081
#define IDC_BUTTON_DOWN                 1082
#define IDC_EDIT_START_ITEM_MID         1082
#define IDC_EDIT_START_ITEM_SID         1083
#define IDC_EDIT1                       1083
#define IDC_EDIT_LEVEL                  1083
#define IDC_EDIT_NEW_ID                 1083
#define IDC_EDIT_START_SKILL_MID        1084
#define IDC_STATIC_LEVEL                1084
#define IDC_EDIT_START_SKILL_SID        1085
#define IDC_EDIT_START_QUEST_MAP_MID    1086
#define IDC_EDIT_TALKNPC_NUM            1086
#define IDC_EDIT_START_QUEST_MAP_SID    1087
#define IDC_EDIT_TALKNPC_NUM2           1087
#define IDC_EDIT_START_QUEST_MAP_X      1088
#define IDC_EDIT_TALKNPC_NUM3           1088
#define IDC_EDIT_START_QUEST_MAP_Y      1089
#define IDC_EDIT_START_LEVEL            1090
#define IDC_EDIT_START_QUEST_MAP_RADIUS 1091
#define IDC_COMBO_SCHOOL                1092
#define IDC_CHECK_EXTREME_M             1093
#define IDC_BUTTON_EDITCANCEL           1094
#define IDC_CHECK_FIGHETER_M            1095
#define IDC_CHECK_ARCHER_M              1096
#define IDC_CHECK_ARMS_M                1097
#define IDC_CHECK_SPIRIT_M              1098
#define IDC_STATE_COMBO1                1099
#define IDC_STATE_COMBO2                1100
#define IDC_STATE_COMBO3                1101
#define IDC_FAIL_CHECK1                 1102
#define IDC_FAIL_CHECK2                 1103
#define IDC_FAIL_CHECK3                 1104
#define IDC_MAP_SELECT_COMBO            1105
#define IDC_MAP_EDIT_BUTTON             1106
#define IDC_MAP_MID_EDIT                1107
#define IDC_MAP_SID_EDIT                1108
#define IDC_LIST_MAP_SELECT             1108
#define IDC_MAP_XPOS_EDIT               1109
#define IDC_MAP_YPOS_EDIT               1110
#define IDC_MAP_GATE_EDIT               1111
#define IDC_USE_PROGRESS_CHECK          1112
#define IDC_STEP_MAP_EDIT_BUTTON        1112
#define IDC_BUTTON_MOVEMAP              1113
#define IDC_STEP_MAP_MID_EDIT           1113
#define IDC_STEP_MAP_SID_EDIT           1114
#define IDC_CHECK_SCIENCE_M2            1114
#define IDC_CHECK_EXTREME_M2            1114
#define IDC_CHECK_SCIENCE_M             1114
#define IDC_STEP_MAP_XPOS_EDIT          1115
#define IDC_STEP_MAP_YPOS_EDIT          1116
#define IDC_STEP_MAP_GATE_EDIT          1117
#define IDC_STEP_MAPID_STATIC           1118
#define IDC_STEP_XY_STATIC              1119
#define IDC_STEP_GATE_STATIC            1120
#define IDC_CHECK_ASSASSIN_M            1121
#define IDC_CHECK_ASSASSIN_W            1122
#define IDC_RADIO_ALL                   1123
#define IDC_RADIO_MAN                   1124
#define IDC_RADIO3                      1125
#define IDC_RADIO_WOMAN                 1125
#define ID_MENUITEM_COPY                32771
#define ID_MENUITEM_PASTE_VALUE         32774
#define ID_MENUITEM_PASTE_NEW           32775
#define ID_MENUITEM_CSV_S1              32777
#define ID_MENUITEM_CSV_LO              32777
#define ID_BUTTON32778                  32778
#define ID_MENUITEM_CSV_SA              32778
#define ID_MENUITEM_QUESTSTEP_MODIFY    32782
#define ID_MENUITEM_QUEST_MODIFY        32783
#define ID_MENUITEM_TEXT_IMPORT         32787
#define ID_MENUITEM_TEXT_EXPORT         32788

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32789
#define _APS_NEXT_CONTROL_VALUE         1126
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
